//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JenningsRE
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class analysis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public analysis()
        {
            this.twenty_five_year_return = new ObservableCollection<twenty_five_year_return>();
        }
    
        public int analysis_id { get; set; }
        public Nullable<double> acquisition_leasing_fee { get; set; }
        public Nullable<double> acquisition_leasing_percentage { get; set; }
        public Nullable<double> syndication_fee { get; set; }
        public Nullable<double> syndication_percentage { get; set; }
        public Nullable<double> land_transfer_tax { get; set; }
        public Nullable<double> land_transfer_percentage { get; set; }
        public Nullable<double> legal_purchase_lease_fee { get; set; }
        public Nullable<double> contingency_tenant_improvement_fee { get; set; }
        public Nullable<double> environmental_fee { get; set; }
        public Nullable<double> construction_fee { get; set; }
        public Nullable<double> mortgage_fee { get; set; }
        public Nullable<double> bcr_fee { get; set; }
        public Nullable<double> appraisal_fee { get; set; }
        public Nullable<double> total_closing_fees { get; set; }
        public Nullable<double> total_acquisition_cost { get; set; }
        public Nullable<double> mortgage_ltv_cost { get; set; }
        public Nullable<double> mortgage_ltv_percentage { get; set; }
        public Nullable<double> twenty_five_year_interest_rate { get; set; }
        public Nullable<double> twenty_five_year_interest_rate_percentage { get; set; }
        public Nullable<double> annual_debt_service_twenty_years { get; set; }
        public Nullable<double> annual_debt_service_twenty_five_years { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<twenty_five_year_return> twenty_five_year_return { get; set; }
    }
}
