//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JenningsRE
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public int expense_id { get; set; }
        public string expense_desc { get; set; }
        public string expense_type { get; set; }
        public double expense_cost { get; set; }
        public string contractor_name { get; set; }
        public Nullable<int> expense_property_id { get; set; }
    }
}
