//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JenningsRE
{
    using System;
    using System.Collections.Generic;
    
    public partial class property
    {
        public int property_id { get; set; }
        public string property_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string postal_code { get; set; }
        public string province { get; set; }
        public string country { get; set; }
        public int rentable_area { get; set; }
        public int available_space { get; set; }
        public int number_of_units { get; set; }
        public string parking_spots { get; set; }
    }
}
