//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JenningsRE
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class tenant
    {
        public int tenant_id { get; set; }
        public string tenant_name { get; set; }
        public int unit_number { get; set; }
        public double unit_size_sqft { get; set; }
        public double rent_per_sf { get; set; }
        public double monthly_rent { get; set; }
        public double annual_rent { get; set; }
        public System.DateTime lease_start { get; set; }
        public System.DateTime lease_end { get; set; }
        public int months_left { get; set; }
        public int tenant_property_id { get; set; }
    
        public virtual property property { get; set; }
    }
}
