//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JenningsRE
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class twenty_five_year_return
    {
        public int return_id { get; set; }
        public int analysis_id { get; set; }
        public Nullable<short> return_year { get; set; }
        public Nullable<double> base_rental_revenue { get; set; }
        public Nullable<double> additional_revenue { get; set; }
        public Nullable<double> slippage { get; set; }
        public Nullable<double> total_revenue { get; set; }
        public Nullable<double> vacancy_bad_debt { get; set; }
        public Nullable<double> interest_payments { get; set; }
        public Nullable<double> principal_payments { get; set; }
        public Nullable<double> total_debt_service { get; set; }
        public Nullable<double> net_operating_income { get; set; }
        public Nullable<double> noi_percentage { get; set; }
        public Nullable<double> internal_rate_of_return_percentage { get; set; }
        public Nullable<double> cash_on_cash_share { get; set; }
        public Nullable<double> total_return_share { get; set; }
    
        public virtual analysis analysis { get; set; }
    }
}
